artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://landcover.ai.linuxpolska.com/download/landcover.ai.v1.zip
  local_data_path: artifacts/data_ingestion/landcover_data.zip
  unzip_dir: artifacts/data_ingestion/landcover_v1